### ISSUE TITLE
Documentation - Combine documentation and resources for RMMFI

### ISSUE THREAD

**Issue by brettevans** [codefordenver/rmmfi#28]
As a RMMFI member, I want documentation and training so that I can actually use the tools that Code for Denver has developed.
- [ ] manual sending emails process - connected to #31
- [ ] emma / salesforce connection possibilities - card #3
- [ ] How to make changes to contact fields and labels - card #44
- [ ] Reports - card #42

**Comment by wdoug** [comment]
- Cover Page
- Acknowledgements
- Table of Contents
- Solutions
  - Solution I
    - Purpose
    - Business Process
    - Instructions
  - Solution II
    - Purpose
    - Business Process
    - Instructions
- So on and so forth
- Troubleshooting
- Support
  - Contact
- Yaaaaay! Happy dance fun time! You have volunteers. :-)

**Comment by wdoug** [comment]
User Documentation: https://docs.google.com/document/d/1jFkYPtwZVmoVEkf8Zxt2vyW1spFey0NRphwjSxxTqbw/edit
